### ISSUE TITLE
Add Support to Open API 3.1 (Feb 2021)

### ISSUE THREAD

**Issue by AMorgaut** [MarketSquare/robotframework-openapidriver#23]
Open API 3.1 adds some useful feature some of them coming from being made fully JSON Schema compliant*
(* with a new JSON Schema spec draft)

Differences Highlighted by the community
- https://blog.stoplight.io/difference-between-open-v2-v3-v31
- https://nordicapis.com/whats-new-in-openapi-3-1-0/
- https://www.youtube.com/watch?v=Sflpzh_cAcA

Announcement from Feb 18, 2021
- https://www.openapis.org/blog/2021/02/18/openapi-specification-3-1-released

Official Incremental Release Notes from v3.0.3
- RC0: https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc0
- RC1: https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0-rc1
- Final: https://github.com/OAI/OpenAPI-Specification/releases/tag/3.1.0

A Migration Guide (incomplete but interesting):
- https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

**Comment by AMorgaut** [comment]
Note: Even without supporting all open API 3.1 features (such as webhooks), it would nice to at least support the schemas changes like arrays for types instead of oneOf

**Comment by robinmackaij** [comment]
@AMorgaut What issues are you running into / what exactly is not working for you? If you have examples of OAS 3.1 documents that contain the new / changed functionality that's currently not handled / supported, that'll help me in adding support. If possible, a public API endpoint implementing the new standard would be ideal.

**Comment by AMorgaut** [comment]
I do think the first step would be to handle the breaking changes to make sure you're at least able to parse Open API documents using the new syntax rules

#### Multiple Examples inside Schema Object

Before
```yaml
schema:
  type: integer
  example: 80
```

Open API 3.1+
```yaml
schema:
  type: integer
  examples:
  - 80
  - 443
```

#### Single-valued Enum and Const

I love this one. 

Before
```yaml
schema:
  type: string
  enum: 
  - "Bad Request"
```

Open API 3.1+
```yaml
schema:
  type: string
  const: "Bad Request"
```

####  The `nullable` keyword has been removed from the Schema Object (`null` can be used as a type value).

Before:
```yaml
schema:
  type: string
  nullable: true
```

3.1+
```yaml
schema:
  type:
  - string
  - 'null'
```

#### `exclusiveMaximum` and `exclusiveMinimum` cannot accept `boolean` values (following JSON Schema).

Before (from JSON Schema Draft 4 & 5)
```yaml
schema:
  type: number
  minimum : 100
  exclusiveMinimum : true
```

Open API 3.1+ /  JSON Schema draft 2019-09 & 2020-12
```yaml
schema:
  type: number
  exclusiveMinimum : 100
```

#### `format` (whether `byte`, `binary`, or `base64`) is no longer used to describe file payloads. As part of JSON Schema compliance, now `contentEncoding` and `contentMediaType` can be used for such specification.

##### Binary File Upload

Before
```yaml
requestBody:
  content:
    application/octet-stream:
      schema:
        type: string
        format: binary
```

Open API 3.1+
```yaml
requestBody:
  content:
    application/octet-stream: {}
```

##### Upload via Multipart Request

Before
```yaml
requestBody:
content:
  multipart/form-data:
    schema:
      type: object
      properties:
        userId:
          type: integer
        picture:
          type: string
          format: binary
```

Open API 3.1+
```yaml
requestBody:
  content:
    multipart/form-data:
      schema:
        type: object
        properties:
          userId:
            type: integer
          picture:
            type: string
            contentMediaType: image/*
```
